### ISSUE TITLE
Add animation

### ISSUE THREAD

**Issue by aivs** [jhautefeuille/garden.gauge#3]
Easy to add animation.

add on top:
```
from kivy.animation import Animation
```

replace:
```
self._needle.rotation = (50 * self.unit) - (self.value * self.unit)
```
with:
```
a = Animation(rotation=(50 * self.unit) - (self.value * self.unit), t='in_out_quad',duration=0.2)
a.start(self._needle)
```

![anim_guage](https://user-images.githubusercontent.com/2894860/53480623-9f107880-3a8c-11e9-8a41-4f7ed3960d28.gif)

**Comment by jhautefeuille** [comment]
Hello,
Thank you for your suggestion. This makes the movement more fluid.
Nevertheless, I leave the code as it is. You have the freedom to forge the project at your convenience.
Good continuation and thank you.
